"""email-unique

Revision ID: 95731e885df3
Revises: cfbd4bd9fdfa
Create Date: 2024-06-27 13:56:55.385171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95731e885df3'
down_revision: Union[str, None] = 'cfbd4bd9fdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_userprofile_email", "UserProfile", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_userprofile_email", "UserProfile", type_="unique")
    # ### end Alembic commands ###
