"""date-field

Revision ID: c91c5f51a9d3
Revises: 44b15b6cce14
Create Date: 2024-06-21 18:31:12.301956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91c5f51a9d3'
down_revision = '44b15b6cce14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('pub_date', sa.DateTime(), nullable=True))
    op.add_column('Posts', sa.Column('pub_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'pub_date')
    op.drop_column('Posts', 'pub_updated')
    # ### end Alembic commands ###